### PR TITLE
fix(Concurrency): Concurrency issue with hashset on MutantPlacer

### LINKED ISSUE #2899: Concurrency issue with hashset on MutantPlacer
**Describe the bug**
_A concurrent update was performed on this collection and corrupted its state_
Since 4.0.3, it throw an exception, while no issue with 4.0.0 (4.0.1 and 4.0.2 was not working because of #2881).
It seems that some parallel stuff was added/modified in 4.0.3 without looking if it was thread safe.

**Logs**
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Stryker.Core.Mutants.MutantPlacer.RegisterEngine(IInstrumentCode engine, Boolean requireRecursive) in /_/src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs:line 53
   at Stryker.Core.Mutants.CsharpNodeOrchestrators.BaseFunctionOrchestrator`1..ctor() in /_/src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BaseFunctionOrchestrator.cs:line 19
   at Stryker.Core.Mutants.CsharpNodeOrchestrators.BaseMethodDeclarationOrchestrator`1..ctor()
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.BuildOrchestratorList() in /_/src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs:line 39
   at Stryker.Core.Mutants.CsharpMutantOrchestrator..ctor(MutantPlacer placer, IEnumerable`1 mutators, StrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs:line 35
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate(MutationTestInput input) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 57
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 88
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, MutationTestInput input, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 38
   at Stryker.Core.Initialisation.ProjectOrchestrator.<>c__DisplayClass7_0.<MutateProjects>b__0(MutationTestInput mutationTestInput) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 70
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Expected behavior**
Should not throw the exception.

**Desktop:**
 - OS: Windows
 - Type of project core, xamarin
 - Framework Version: AspNet core 8
 - Stryker Version 4.0.3

**Additional context**
It happens right after building and discovering the tests.
_[09:21:05 INF] Number of tests found: 1 for project C:\Dev\AnySolution\AnyProject.csproj. Initial test run started.
[09:21:27 ERR] An error occurred during the mutation test run_

### PR DESCRIPTION
**Pull request by richardwerkman**
closes #2899

### CODE REVIEW

**Comment by richardwerkman** [comment]
@dupdob do you see any issues with this change? I don't know the reason behind these fields being static. Probably for performance reasons, but if there was another reason this PR might have some unexpected effects.

**Comment by dupdob** [comment]
@richardwerkman : sorry, I was off last week and missed your message. I did not had an opportunity to look into this yet (will do early this week). 
My gut answer is that it is probably easier to keep the static bits and protect them with a lock than to go through the likely hassle to make them instance variable. But as said earlier, I need to take a look at the code to reach for conclusion.

**Comment by richardwerkman** [comment]
Thanks for your view on this. I already did the work so we could not take the work needed into account. When I read the code I noticed it isn't stateless completely, that's why I changed it away from static. 

@rouke-broersma what do you think? Revert to static and add a lock, or keep the change as is.

**Comment by dupdob** [comment]
I opened PR #2916 to demonstrate my alternate approach, which has the great benefit of requiring only a few changes.

**Pull request closed without merging**
