### PR TITLE
fix: exception when source files in more than one test project

### PR DESCRIPTION
**Pull request by dupdob**
Fix issue #2538

### CODE REVIEW

**Comment by rouke-broersma** [comment]
@dupdob I don't know why but both of your recent PRs for some reason have an infinite wait in the unit test in the pipeline, I cannot reproduce this locally..

**Comment by dupdob** [comment]
I have not idea what is happening. From what I understands looking at Azure logs, the tests don't even start...

**Comment by dupdob** [comment]
Since PRs impact very different files, it looks like a flaky test situation, that is probably triggered by a change in timing, which can be due to many things: new tests, tests order change, upgrades/changes on azure side...

**Comment by dupdob** [comment]
Well, my first guess was clearly spot on: the problem comes from SseServerTests: those are flaky and prone to deadlock.
But not sure how to get out of these...

**Comment by rouke-broersma** [comment]
I'll ask @xandervedder to take a look

**Comment by xandervedder** [comment]
I think what we might need to do is use a different http listener implementation (one that is easier to test), but that would require a new dependency. I also struggled a lot with this unfortunately.

**Pull request merged**
