### PR TITLE
feat(html reporter): Update to mutation testing elements 1.3.0

### LINKED ISSUE #885: When using --diff, the mutation-report.html shows 100% mutation score on files that were not mutated
**Describe the bug**
When running the command:
```dotnet-stryker --diff -gs "branch" -r "['html']"``` 

The mutation-report.html shows 100% mutation score on files that were not mutated.
Stryker100diff

**Expected behavior**
I would expect the report to show any files that were not tested as something like skipped, N/A, or 0.

**Desktop:**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: Core 2.2
 - Stryker Version 0.15.0 beta

### PR DESCRIPTION
**Pull request by richardwerkman**
Fixes #885

Includes support for correctly reporting 0 mutants in a file and Ignored mutant status

### CODE REVIEW

**Comment by Mobrockers** [comment]
The mutation status Ignored has been added in this version as well: https://github.com/stryker-mutator/mutation-testing-elements/pull/239

Since we use Skipped internally we won't be filling the correct schema property with the data to display this status in the reports. We need to either change status Skipped to Ignored in our sources or translate from Skipped to Ignored in the JsonReport.

**Comment by richardwerkman** [comment]
@Mobrockers I've changed the status to Ignored as you said.

**Pull request merged**
