### PR TITLE
fix(git diff filter): Gitignore was incorrectly placed causing strykeroutput to show in diff filter

### PR DESCRIPTION
**Pull request by g7ed6e**
…tch changes from given commit

### CODE REVIEW

**Comment by Mobrockers** [comment]
@g7ed6e Can you confirm that this has the wanted effect? Or do I need to run this change in a pipeline to determine if it worked?

**Comment by g7ed6e** [comment]
@Mobrockers I did not tested it yet. To test it i need to build the package and run it outside of the dotnet-stryker repo due to this issue #1209 . Please run it into a dedicated pipeline with the diff arg only to confirm it works as expected.

**Comment by Mobrockers** [comment]
```
[18:56:46 INF] 3 files changed
[18:56:46 INF] Changed file D:\a\1\s\src\Stryker.CLI\Stryker.CLI.UnitTest\StrykerOutput\.gitignore
[18:56:46 INF] Changed file D:\a\1\s\src\Stryker.CLI\Stryker.CLI.UnitTest\StrykerOutput\2020-10-10.18-56-02\logs\VsTest-log.host.20-10-10_18-56-42_50191_7.txt
[18:56:46 INF] Changed file D:\a\1\s\src\Stryker.CLI\Stryker.CLI.UnitTest\StrykerOutput\2020-10-10.18-56-02\logs\VsTest-log.txt
```

It doesn't appear to fix the issue.

I am starting to think perhaps the gitignore doesn't get created at all.

**Comment by Mobrockers** [comment]
Yep, the actual issue is that the gitignore does not get created..
``` 
[19:27:26 ERR] Could't create gitignore because of error The process cannot access the file 'D:\a\1\s\src\Stryker.CLI\Stryker.CLI.UnitTest\StrykerOutput\.gitignore' because it is being used by another process.
```

**Comment by Mobrockers** [comment]
Changing the way the gitignore file was created helped a bit ;) 

```
[19:54:21 INF] 0 files changed
[19:54:21 INF] Total number of tests found: 66
[19:54:21 INF] Initial testrun started
[19:54:26 INF] Using 12800 ms as testrun timeout
[19:54:32 INF] Capture mutant coverage using 'perTest' mode.
[19:54:36 INF] 2     mutants got status CompileError. Reason: Mutant caused compile errors
[19:54:36 INF] 6     mutants got status NoCoverage.   Reason: Mutant has no test coverage
[19:54:36 INF] 215   mutants got status Ignored.      Reason: Mutant not changed compared to target commit
[19:54:36 INF] 223   total mutants are skipped for the above mentioned reasons
[19:54:36 INF] 0     total mutants will be tested
[19:54:36 WRN] It looks like all mutants with tests were excluded. Try a re-run with less exclusion!
[19:54:36 WRN] It looks like all non-excluded mutants are not covered by a test. Go add some tests!
```

**Pull request merged**
