### PR TITLE
Potential fix for handling self-contained apps

### PR DESCRIPTION
**Pull request by psfinaki**
#1855 

See discussion [here](https://github.com/daveaglick/Buildalyzer/pull/194).

So technically this is not a pinpoint solution for the original problem, in that it fixes the problem in quite a dramatic way. 
On the other hand, from what I understand, similar problems were encountered before, probably for the same reason. So maybe it's worth applying as a prevention.

Giving that you guys here know quite a lot of stuff about MSBuild and I don't, this PR is partially meant as a discussion :) thoughts?

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Setting design time to false in all cases will impact the performance of Stryker in all cases so I don't think that is a viable solution. We should probably detect whether or not we are in a self-contained scenario and apply the workaround if necessary. But this feels like something that should be in Buildalyzer and not in Stryker. It seems like @daveaglick agrees and is open to discussion about the proper fix for this problem. It seems to me like the solution would be exactly the same whether it is applied in Buildalyzer or in Stryker so I would say fixing it in Buildalyzer has the most impact. It would fix the problem for all consumers.

**Comment by psfinaki** [comment]
Yes, that's true, my point was to ask if this change will benefit Stryker in any other way. I mean the drawback is clear (some performance) but the extra information got from the build might be useful somehow.

If not, that yes ignore this PR, I'm working on fixing the actual problem in Buildalyzer anyway.

**Comment by rouke-broersma** [comment]
Don't know if there is any benefit to doing a full build so I can't answer that. We already do a full build after buildalyzer using either msbuild or dotnet build but that's just to test if the project is actually buildable. We might be able to replace that first build by using buildalyzer for everything? @richardwerkman what do you think

**Comment by daveaglick** [comment]
The discussion about this has been ongoing over at Buildalyzer, but just some quick comments to close the loop here...

> Setting design time to false in all cases will impact the performance of Stryker in all cases so I don't think that is a viable solution.

I'd also suggest we try to figure out how to continue using design-time builds. They can be an order-of-magnitude faster in some cases, and even though this has been a tricky one to solve, I have no doubt we'll find a way to perform design-time builds on self-contained apps given that Visual Studio can do it.

> But this feels like something that should be in Buildalyzer and not in Stryker.

I totally agree - being able to correctly analyze self-contained vs. non-self-contained applications isn't unique to Stryker and so I think it absolutely should be handled as well as we can upstream in Buildalyzer.

> Also: I know more about MSBuild than I care to, which is just enough to know that I don't want to know more, but also that I probably should know more for the benefit of Stryker

It me :)

**Comment by rouke-broersma** [comment]
Closed in favor of #1868

**Pull request closed without merging**
