### PR TITLE
fix(Mutator names): Update mutator names in readme

### PR DESCRIPTION
**Pull request by nobuyuki1965**
The names changed in a previous PR

### CODE REVIEW

**Comment by nobuyuki1965** [comment]
Good

**Comment by nobuyuki1965** [comment]
Good job

**Comment by nobuyuki1965** [comment]
Nice easy

**Comment by nobuyuki1965** [comment]
Ok

**Comment by nobuyuki1965** [comment]
Approved

**Comment by ptoonen** [comment]
This was already merged in #258.

**Pull request closed without merging**
