### PR TITLE
fix: Improve MsBuild detection 

### PR DESCRIPTION
**Pull request by dupdob**
Review existing logic around MsBuild in order to: improve MsBuild version selection, reduce search time and increase reliability
For initial build, Stryker now uses:
1) dotnet build
2) dotnet msbuild or msbuild.exe if (1) fails (see (a) below)
3) if (2) fails, a `dotnet msbuild -t:restore -p:RestorePackagesConfig=true`  is done (assumption is the project still uses `package.config` files). Note this works only for v16+ MsBuild versions (see (b) below).

Likewise, the nuget restore done during project analysis phase is done using the same msbuild version as for initial build.

### a. MsBuild version detection
Stryker selects MsBuild via
1) user configuration if provided, otherwise
2) version detected by BuildAlyzer (via `EnvironmentFactory` class). If it fails
3) legacy detection logic 
Note that it looks impossible for Stryker to complete successfully if Buildalyzer fails to identify the proper MsBuild version.

One of the benefits of this approach is Stryker can now use MsBuild even on non Windows platform (via dotnet msbuild.exe). This could fix some building issues on linux pipelines.
Another benefits is that Stryker spends some time to locate MsBuild at startup, this is no longer the case: MsBuild location search happens only if everything else fails. Likewise, this search happens twice in current Stryker version.

### b. Restore logic
This version does not bring significant improvments on existing package restore logic. I suppose logic could be improved by:
1) detecting the presence of `package.config` file (instead of assuming it). But dotnet build already performs a package restore for SDK style project, so this is a fair assumption
2) using nuget.exe could lead to better results for legacy style project and is required if there are only old MsBuild version

I did not work on this because tests were hard to write so guaranteeing proper results appears to be difficult

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Do we really need the fallbacks to dotnet msbuild and the legacy msbuild detection? I'm not sure if using msbuild for dotnet core projects has ever proven successful in solving build issues. I also feel like if buildalyzer cannot detect msbuild there is no point in continuing to search for msbuild. Wdyt?

**Comment by dupdob** [comment]
Experience shows that build phase is quite sensitive to user specific setups and CIs. So I preferred to keep the legacy code for the time being just in case some people ran into issues, especially since it has no impact whatsoever in behaviour
Having it at hand could be useful to fix a problem. But it should go in the short term, yes. I would suggest keeping it for a single release only.

**Comment by rouke-broersma** [comment]
For some reason the integration test fails on macos. Perhaps something with paths?

```
[13:26:57 INF] Analysis starting.
[13:26:57 INF] Analyzing 2 test project(s).
[13:27:03 INF] Found project /Users/runner/work/1/s/integrationtest/TargetProjects/NetCore/TargetProject/TargetProject.csproj to mutate.
[13:27:03 INF] Analysis complete.
[13:27:03 INF] Building test project /Users/runner/work/1/s/integrationtest/TargetProjects/NetCore/NetCoreTestProject.NUnit/NetCoreTestProject.NUnit.csproj (1/2)
[13:27:03 INF] Building project  using dotnet build NetCoreTestProject.NUnit.csproj
[13:27:03 ERR] Initial build failed: MSBUILD : error MSB1009: Project file does not exist.
Switch: NetCoreTestProject.NUnit.csproj

[13:27:03 INF] Time Elapsed 00:00:06.6215503
Stryker.NET failed to mutate your project. For more information see the logs 
below:


MSBUILD : error MSB1009: Project file does not exist.
Switch: NetCoreTestProject.NUnit.csproj


Initial build of targeted project failed. Please make sure the targeted project 
is buildable. You can reproduce this error yourself using: "dotnet build 
NetCoreTestProject.NUnit.csproj"

```

**Comment by dupdob** [comment]
> For some reason the integration test fails on macos. Perhaps something with paths?
> 
> ```
> [13:26:57 INF] Analysis starting.
> [13:26:57 INF] Analyzing 2 test project(s).
> [13:27:03 INF] Found project /Users/runner/work/1/s/integrationtest/TargetProjects/NetCore/TargetProject/TargetProject.csproj to mutate.
> [13:27:03 INF] Analysis complete.
> [13:27:03 INF] Building test project /Users/runner/work/1/s/integrationtest/TargetProjects/NetCore/NetCoreTestProject.NUnit/NetCoreTestProject.NUnit.csproj (1/2)
> [13:27:03 INF] Building project  using dotnet build NetCoreTestProject.NUnit.csproj
> [13:27:03 ERR] Initial build failed: MSBUILD : error MSB1009: Project file does not exist.
> Switch: NetCoreTestProject.NUnit.csproj
> 
> [13:27:03 INF] Time Elapsed 00:00:06.6215503
> Stryker.NET failed to mutate your project. For more information see the logs 
> below:
> 
> 
> MSBUILD : error MSB1009: Project file does not exist.
> Switch: NetCoreTestProject.NUnit.csproj
> 
> 
> Initial build of targeted project failed. Please make sure the targeted project 
> is buildable. You can reproduce this error yourself using: "dotnet build 
> NetCoreTestProject.NUnit.csproj"
> ```

Yep, looking into it

**Pull request merged**
