### PR TITLE
docs(contributor): Update Contributors Guide

### PR DESCRIPTION
**Pull request by ptoonen**
Include the commit guidelines as proposed in #275

### CODE REVIEW

**Comment by richardwerkman** [comment]
Well actually I removed it intentionally. Since contributors should not have to worry about the naming of commits. When merging to master we (maintainers) squash the commits into a new commit which should be conform the angular style guide. 

We could also change it to be a Maintainer specific part of the contribution guide?

**Comment by Mobrockers** [comment]
If contributors happen to read the contributing guidelines they can use the recommended commit style and we won't have to change their message for them, I don't see any harm keeping it in there.

**Comment by richardwerkman** [comment]
But when we select the squash option on a PR the name of the PR is selected as the name for the squash commit. So then we should put it down as a PR style guide?

**Comment by ptoonen** [comment]
I was thinking about that too (calling it a PR guideline) - although I see this more as a guideline than as a strictly enforced rule. For now it's easy for maintainers to do this properly, however as the project grows larger, it would be nice if contributors help you there.

**Pull request merged**
