### PR TITLE
should dispose of process

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Could you target this to the v1 branch? We're not currently accepting prs to master.

**Comment by SimonCropp** [comment]
done

**Comment by richardwerkman** [comment]
Thanks for this fix! It seems we overlooked this one. I have one question? Did you find this after you encountered a bug? We have not noticed anything before but maybe we missed something. In any case, thanks for the contribution :)

**Comment by SimonCropp** [comment]
@richardwerkman i was just reading the code and noticed. I am not currently using stryker

**Pull request merged**
