### PR TITLE
Automatically disable DiffEngine when running tests

### PR DESCRIPTION
**Pull request by 0xced**
Disable DiffEngine so that approval tests frameworks such as [Verify](https://github.com/VerifyTests/Verify) or [ApprovalTests.Net](https://github.com/approvals/ApprovalTests.Net) (which both use DiffEngine under the hood) don't launch a diffing tool GUI on each failed test.

### CODE REVIEW

**Comment by rouke-broersma** [comment]
This sounds more like a feature than a bugfixes, though the impact is likely small. @richardwerkman you think this is fine to put on master?

@0xced  Would there ever be a case where someone would actually want to disable this behavior? My instinct says probably not but I am not familiar with this class of test tooling.

**Comment by 0xced** [comment]
> Would there ever be a case where someone would actually want to disable this behavior?

Approval testing is useful when doing TDD and running test by test but running mutation tests is the opposite, many tests are going to fail (the diffing tool are launched only on failed tests). So I can't imagine a scenario in which you would want dozen or maybe even hundreds of diffing tool instances to start when running the mutation tests.

**Comment by richardwerkman** [comment]
I think we can see this as a bug fix. It's undesired behaviour and I don't see any harm in releasing this before v1.

**Comment by rouke-broersma** [comment]
@0xced this fix will be released shortly

**Pull request merged**
