### PR TITLE
fix: Add node orchestrator for global statements

### LINKED ISSUE #3073: Stryker disable comment not working for global statements
**Describe the bug**

I have a .NET 8 Web API whose "Program.cs" contains the code below.

image

The variable `SWAGGER_MODULE` is set when the project compiles with the "DEBUG" configuration, and not set when it compiles with the "RELEASE" configuration. Eitherway, note how the `// Stryker disable all` is outside of the `#if`. Still, the code gets mutated. (This is also the case if I move the `// Stryker disable all` inside the `#if`.)

Why does `// Strykler disable all` not work?

**Logs**

Stryker takes several hours on this very big project. I can run it over night and deliver the logs if really required.

**Expected behavior**

I expect that the code between `// Stryker disable all` and `// Stryker restore all` is not mutated.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project: .NET 8 Web API
 - Framework Version: .NET 8 Web API
 - Stryker Version: 4.3.0

### LINKED ISSUE #3081: Stryker messes with compiler directives
**Describe the bug**
Mutated code may end up containing ill-formed compiler directives. I.e, Stryker does not ensure directives appear at the beginning of source lines. They may end up being captured within flow control statements.

**Logs**
When mutating this method
```csharp
public void SomeMethod() {
    var x = 0;
#if !DEBUG
    x++;
#endif
}
```
Stryker generates this version
```csharp
public void SomeMethod() {if(StrykerNamespace.MutantControl.IsActive(0)){}else{
    var x = 0;
if(StrykerNamespace.MutantControl.IsActive(1)){;}else{if(StrykerNamespace.MutantControl.IsActive(2)){#if !DEBUG
    x--;
}else{#if !DEBUG
    x++;
}}#endif
}}
```

**Expected behavior**
Compiler directives should not be transformed by the mutation step. 
Previous example should result in something like this:
```csharp
public void SomeMethod() {if(StrykerNamespace.MutantControl.IsActive(0)){}else{
    var x = 0;
#if !DEBUG
if(StrykerNamespace.MutantControl.IsActive(1)){;}else{if(StrykerNamespace.MutantControl.IsActive(2)){    x--;
}else{
    x++;
}}
#endif    
}}
```

**Desktop (please complete the following information):**
 - OS: NA
 - Type of project NA
 - Framework Version NA
 - Stryker Version 4.3 , and earlier versions

### PR DESCRIPTION
**Pull request by dupdob**
Fix issues with global statements, such as handling of stryker comments and complex mutation declarations (block level).
Declare an orchestrator for global statements. For some reason, the GlobalStatementSyntax class inherits from MemberDefinitionSyntax, which does not lead to the expected behavior: Stryker treats Member Definition as hard barriers.
fix #3081
fix #3073

### CODE REVIEW

**Comment by dupdob** [comment]
Oups. I forgot this PR was still in draft, so I missed merge Friday
Sorry about this.

**Comment by rouke-broersma** [comment]
Merge friday, I like it :D

**Comment by richardwerkman** [comment]
@dupdob thanks for fixing this! Looks good, I'm just thinking this could be something we want to add to the integration test as well. We currently don't have any top-level statements in the integration test project. But I suggest creating a separate issue for that so we can release this fix quickly (I want to release today). Would you agree?

**Comment by cfuehrmann** [comment]
Thanks for fixing this! Looking forward to trying this as soon as I get my hands on the next stryker-net release.

**Comment by richardwerkman** [comment]
@cfuehrmann the release is out the door! So you can try it if you want

**Comment by cfuehrmann** [comment]
I can confirm from our nightly runs that the issue is indeed fixed. Thanks ever so much!

**Pull request merged**
