### PR TITLE
Options to include or exclude LinqExpressions on LinqMutator

### PR DESCRIPTION
**Pull request by leonardosimoura**
PR for #1546

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Hi @leonardosimoura 👋 

We are currently reworking all options in #1273 
I don't think we will want an option like this to be a commandline option (so config file only) in the new design. We will take a look at your pull request when we are done reworking all the options infrastructure. We will implement the needed changes to the options at that time. Hope that's alright with you.

**Comment by leonardosimoura** [comment]
Hi @rouke-broersma 

It's OK,  i will follow the #1273 for new updates
Thanks for the attention

**Comment by richardwerkman** [comment]
@leonardosimoura just a heads up, #1273 has been merged so you can update your PR with our new options.

I do have a note though. I'd rather have this not a new option. We could add it to the current option like this:
``` json
{
  "stryker-config": {
    "ignore-mutations": [
      "string",
      "linq.FirstOrDefault"
    ]
}
```
this option is already config file only like @rouke-broersma described. 

And some other remarks:
We have a mechanism to filter mutations without changing the mutator like you did. In the folder `MutationFilters` you can find some [examples](https://github.com/stryker-mutator/stryker-net/blob/v1.0/src/Stryker.Core/Stryker.Core/MutantFilters/ExcludeMutationMutantFilter.cs). If you need help working with the new options or the mutant filters please let us know. We are happy to help.

**Comment by richardwerkman** [comment]
I've created #1656 for some guidance.

**Comment by leonardosimoura** [comment]
Hi @richardwerkman  thanks for attention.
I will abandon this PR, refactor the solution and open a new PR.

**Pull request closed without merging**
