### PR TITLE
feat: replace camel case arguments with dashed (#100)

### PR DESCRIPTION
**Pull request by KonH**
Related to #100

### CODE REVIEW

**Comment by simondel** [comment]
Thanks for creating this pr! We'll look at it :) Feel free to ignore the Azure Pipelines build for now.

**Comment by simondel** [comment]
Suggested commit message when merging:
```
feat(cli): replace camel case arguments with dashed arguments


Fixes #100

BREAKING CHANGES:
Renamed command line arguments and config setting names. `timeoutMS` is now called `timeout-ms`. `logConsole` is now called `log-console`. `logFile` is now called `log-file`. `projectName` is now called `project-name`.
```

**Comment by simondel** [comment]
By the way @yaelkeemink Is it intentional that the project argument for command line is `--project` while in the config file it's `--project-name`?

**Comment by yaelkeemink** [comment]
No it is not intentional. I would rather see '--project-file' instead of --project or --project-name since it is more descriptive.

**Pull request merged**
