### PR TITLE
Temp fix gitinfoprovider

### PR DESCRIPTION
**Pull request by Mobrockers**

### CODE REVIEW

**Comment by Mobrockers** [comment]
Result:

```
[16:32:24 DBG] Sending GET to https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker-net/dashboard-compare/?module=cli
[16:32:25 INF] We could not locate a baseline for branch , now trying fallback version master
[16:32:25 DBG] Sending GET to https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker-net/master?module=cli
[16:32:25 INF] Found fallback report using version master
```

project version should have been used here...

**Comment by Mobrockers** [comment]
[17:21:21 DBG] Could not locate the current branch name, using project version instead: temp-fix-gitinfoprovider
[17:21:21 DBG] Sending GET to https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker-net/dashboard-compare/temp-fix-gitinfoprovider?module=cli
[17:21:21 INF] Found baseline report for current branch temp-fix-gitinfoprovider

**Comment by g7ed6e** [comment]
> [17:21:21 DBG] Could not locate the current branch name, using project version instead: temp-fix-gitinfoprovider
> [17:21:21 DBG] Sending GET to https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker-net/dashboard-compare/temp-fix-gitinfoprovider?module=cli
> [17:21:21 INF] Found baseline report for current branch temp-fix-gitinfoprovider

From my pov git diff feature should work standalone.

**Comment by Mobrockers** [comment]
> > [17:21:21 DBG] Could not locate the current branch name, using project version instead: temp-fix-gitinfoprovider
> > [17:21:21 DBG] Sending GET to https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker-net/dashboard-compare/temp-fix-gitinfoprovider?module=cli
> > [17:21:21 INF] Found baseline report for current branch temp-fix-gitinfoprovider
> 
> From my pov git diff feature should work standalone.

Yes, it should

**Comment by g7ed6e** [comment]
> > > [17:21:21 DBG] Could not locate the current branch name, using project version instead: temp-fix-gitinfoprovider
> > > [17:21:21 DBG] Sending GET to https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker-net/dashboard-compare/temp-fix-gitinfoprovider?module=cli
> > > [17:21:21 INF] Found baseline report for current branch temp-fix-gitinfoprovider
> > 
> > 
> > From my pov git diff feature should work standalone.
> 
> Yes, it should

Thus to détermine if it works we should not rely on dashboard compare configuration but only on diff cmd line arg and comparison with azure devops detected changed files. How the stryker on stryker task is configured ?

**Pull request closed without merging**
