### PR TITLE
chore: Add issue template configuration

### PR DESCRIPTION
**Pull request by Mobrockers**
Gives us something like this:

image

### CODE REVIEW

**Comment by Mobrockers** [comment]
@richardwerkman what do ya think

**Comment by richardwerkman** [comment]
It looks good but didn't we want to direct questions towards Github Discussions? If so, we don't want to send people to slack also.

**Comment by Mobrockers** [comment]
Do we want to completely move away from slack? I deliberately expressed it as talking (chatting) with the team on slack and asking questions and such to github discussions.

**Comment by richardwerkman** [comment]
Sorry I oversaw the `Ask a Question` part. Looks good to me then

**Pull request merged**
