### PR TITLE
Calming down source generation messages

### PR DESCRIPTION
**Pull request by psfinaki**
This is related to the discussion in #1413.

We've been enjoying source generation working for a while and haven't encountered any other related issues but yeah this creates a lot of noise which after this "probation period" can be probably silenced a bit. 

Feel free to discard this if you want - it was not a big effort to create :D

### CODE REVIEW

**Comment by rouke-broersma** [comment]
I don't think this should be downgraded, rather the situations where it shows up should be fixed so it is no longer an issue. If this happens your mutation result might not be completely accurate which we should report to the user.

@dupdob what do you think

**Comment by psfinaki** [comment]
Fair, as I say, if you feel there can be a scenario when this message can actually be helpful rather than scaring, we don't need to make it quieter. My idea was to calm it down until we actually see such a scenario.

**Comment by dupdob** [comment]
Issue #1650 tracks this problem and related discussions. I suggest further discussions to happen there and I close this PR as it is too radical a solution

To summarize the problem:
1. Code generators support are a must have for proper compilation moving forward.
2. Code generators are piggy packed over Code Analyzers support infrastructure.
3. Analyzers prove to be difficult to load at compile time while this is a needed feature (as per issue #1534).
4. It is crucial to log when Stryker fails to load a Code Generator as it will result in a failed compilation
5. We cannot distinguish between an analyzer or a code generator without loading them

**Comment by psfinaki** [comment]
@dupdob thanks for the prompt reaction :) 
No problem, I hope we can address this properly then, I will create an issue in our internal backlog for this, in the end it's an interesting nut to crack.

**Pull request closed without merging**
