### PR TITLE
feat(ui): make console output more readable

### PR DESCRIPTION
**Pull request by draptik**
Using Serilog's AniConsoleTheme.Sixteen improves readability of the console log output on dark and light background consoles. See https://github.com/stryker-mutator/stryker-net/issues/3046 for details.

### CODE REVIEW

**Comment by rouke-broersma** [comment]
@draptik I'm testing out the change on my own system and the default theme already seems to be working fine for me on light themes. Coupled with the note by the serilog team that ansi themes don't work well on cmd that makes me hesitant to approve the change.

Could there by anything in your specific environment configuration that's affecting this? If I run the latest released version of stryker in the VS console with light theme the console output colour is black, not white as in yours:

image


In fact if you look at your own example you can see that the default colour for the terminal seems to actually be white, because all other printed text is also white:

image

So it seems to me like serilog is actually following the configured terminal colors.

**Comment by draptik** [comment]
OK, understood. Thanks for the update!
Since this issue seems to be more involved than I initially thought, feel free to discard this PR.

**Comment by rouke-broersma** [comment]
> OK, understood. Thanks for the update!
> Since this issue seems to be more involved than I initially thought, feel free to discard this PR.

Could you give some more information on your terminal theme/configuration so we could determine whether the results you're seeing are intentional or not?

**Comment by draptik** [comment]
Sure.
- linux: [kitty terminal](https://sw.kovidgoyal.net/kitty/) "Tango Light" / "Tango Dark"
- windows: Windows Terminal "Tango Light" / Tango Dark"
- Rider (linux/windows): built-in terminal with "Rider Dark" / "Rider Day" themes.

**Pull request closed without merging**
