### PR TITLE
feat(nuget): Make nuget restore errors non fatal

### LINKED ISSUE #3067: MSBuild could not be found - issue with NuGet
**Describe the bug**

we´ve updated our stryker vorm V4.06 to V4.3.0 but now I get the following error while mutating a project. We are using .net-framework 4.6.1. so far I can tell msbuild version 15 is installed. Could you please review the error and lead to a solution?

**Logs**
```
`2024-10-16T14:09:51.0597257+02:00  [FTL] Failed to restore nuget packages. Nuget error: "Failed to load msbuild Toolset
  Die Datei oder Assembly \"Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
" (5cc89b77)
2024-10-16T14:10:02.4407505+02:00  [DBG] Restoring packages using command: "C:\Users\felix.arnold\AppData\Local\AzureFunctionsTools\Releases\1.13.2\cli_x64\NuGet.exe" "restore \"C:\source\repos\tfs\Something\11 Source code\Trunk\C#\C3000\C3000.sln\" -MsBuildVersion \"17.7.2.37605\"" (649441ac)
2024-10-16T14:10:02.4413006+02:00  [DBG] Restoring packages using command: "C:\Users\felix.arnold\AppData\Local\AzureFunctionsTools\Releases\1.13.2\cli_x64\NuGet.exe" "restore \"C:\source\repos\tfs\Something\11 Source code\Trunk\C#\C3000\C3000.sln\" -MsBuildVersion \"17.7.2.37605\"" (649441ac)
2024-10-16T14:10:02.7042795+02:00  [FTL] Failed to restore nuget packages. Nuget error: "Failed to load msbuild Toolset
  Die Datei oder Assembly \"Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
" (5cc89b77)
2024-10-16T14:10:02.7165744+02:00  [FTL] Failed to restore nuget packages. Nuget error: "Failed to load msbuild Toolset
  Die Datei oder Assembly \"Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
" (5cc89b77)
2024-10-16T14:10:02.7175197+02:00  [INF] Analysis complete. (f039f576)
2024-10-16T14:10:02.7349404+02:00  [ERR] An error occurred during the mutation test run  (2ecaed66)
System.AggregateException: One or more errors occurred. (Nuget.exe failed to restore packages for your solution. Please review your nuget setup.) (Nuget.exe failed to restore packages for your solution. Please review your nuget setup.) (Nuget.exe failed to restore packages for your solution. Please review your nuget setup.)
 ---> 
Nuget.exe failed to restore packages for your solution. Please review your nuget setup.
WARNUNG: Failed to load C:\Users\felix.arnold\AppData\Local\AzureFunctionsTools\Releases\1.13.2\cli_x64\Microsoft.Azure.WebJobs.Extensions.dll
Die Datei oder Assembly "Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Stryker.Core.Initialisation.InputFileResolver.AnalyzeAllNeededProjects(List`1 projectList, StrykerOptions options, IAnalyzerManager manager, ScanMode mode) in /_/src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs:line 174
   at Stryker.Core.Initialisation.InputFileResolver.AnalyzeAndIdentifyProjects(List`1 projectList, StrykerOptions options, IAnalyzerManager manager, ScanMode mode) in /_/src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs:line 124
   at Stryker.Core.Initialisation.InputFileResolver.ResolveSourceProjectInfos(StrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs:line 66
   at Stryker.Core.Initialisation.InitialisationProcess.GetMutableProjectsInfo(StrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs:line 57
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters, ITestRunner runner) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 52
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 63
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 151
   at Stryker.CLI.StrykerCli.<>c__DisplayClass11_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 123
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
 ---> (Inner Exception #1) 
Nuget.exe failed to restore packages for your solution. Please review your nuget setup.
WARNUNG: Failed to load C:\Users\felix.arnold\AppData\Local\AzureFunctionsTools\Releases\1.13.2\cli_x64\Microsoft.Azure.WebJobs.Extensions.dll
Die Datei oder Assembly "Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
<---
 ---> (Inner Exception #2) 
Nuget.exe failed to restore packages for your solution. Please review your nuget setup.
WARNUNG: Failed to load C:\Users\felix.arnold\AppData\Local\AzureFunctionsTools\Releases\1.13.2\cli_x64\Microsoft.Azure.WebJobs.Extensions.dll
Die Datei oder Assembly "Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)`
```

**Expected behavior**
The new version should work like the previouse.

**Desktop (please complete the following information):**
 - OS: windows
 - C#, partly WPF
 - .net-framework 4.6.1
 - 4.3.0

### PR DESCRIPTION
**Pull request by dupdob**
Slight change: make nuget failures non fatal (log error but continue), as it makes no sense for the general case, especially since selecting the proper msbuild and nuget combination is tricky on complex environment.

Having a proper handling of nuget version would be better, but not sure it is worth the needed effort

Fixes #3067.

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Nuget restore is not optional iirc because buildalyzer performs a clean which deletes the packages, I'm not sure this would be a valid scenario?

**Comment by dupdob** [comment]
Well, in practice, Stryker only make a package restore attempt if the analysis is failed. Judging by the log the author of #3067 provided me, Nuget restore did not even happen in V4.0.6 for his/her project. It happens only with V4.1+ (because 1 project analysis fails for some reason). In any case, this results in aborting the whole mutation session, which is a shame.

Digging into Nuget issues, I discovered that 'unable to find MsBuild version xxx' was a recurrent issue with no clear solution nor workaround, so I am not sure we can fix this properly.

As an alternative, we could also retry a failed nuget session WITHOUT specifying the msbuild version.
But should we abort is this also fails?

**Comment by dupdob** [comment]
remark: I did not notice there was a test explicitly testing for failure; my test runner (NCrunch) does not support yet the platform conditional attributes 😄 , so this test is not visible on my ide.
My bad

**Comment by rouke-broersma** [comment]
> Well, in practice, Stryker only make a package restore attempt if the analysis is failed. Judging by the log the author of #3067 provided me, Nuget restore did not even happen in V4.0.6 for his/her project. It happens only with V4.1+ (because 1 project analysis fails for some reason). In any case, this results in aborting the whole mutation session, which is a shame.
> 
> Digging into Nuget issues, I discovered that 'unable to find MsBuild version xxx' was a recurrent issue with no clear solution nor workaround, so I am not sure we can fix this properly.
> 
> As an alternative, we could also retry a failed nuget session WITHOUT specifying the msbuild version. But should we abort is this also fails?

Yes that makes sense. We added the nuget version because of other conflicts between nuget version and msbuild version, but if it fails regardless we might retry without a specific version.

If I remember correctly we used to even do restore -> analyze -> restore because analyze would always fail without restore, but the analzse would clear the nuget packages and then compilation would not work. Not sure if this is still what we do nor if it's still relevant, but iirc this is how we first made dotnet framework support functional.

But now that I think about it, the restore might only be mandatory for projects that use nuget.config + .packages folder instead of PackageReference and global package cache, so for modern (dotnet framework) sdk style projects it might no longer be required for analyze.

**Comment by dupdob** [comment]
> If I remember correctly we used to even do restore -> analyze -> restore because analyze would always fail without restore, but the analzse would clear the nuget packages and then compilation would not work. Not sure if this is still what we do nor if it's still relevant, but iirc this is how we first made dotnet framework support functional.

I remember it too.

> But now that I think about it, the restore might only be mandatory for projects that use nuget.config + .packages folder instead of PackageReference and global package cache, so for modern (dotnet framework) sdk style projects it might no longer be required for analyze.

I made some attempts to discover when nuget was needed when I rewrote the project analysis phase (hoping to get rid of it altogether): failed to understand when and why it was needed. But it is still sometimes needed. 🤷‍♂️ 

I added a retry logic without msbuildversion.

**Comment by dupdob** [comment]
lol, it looks like we were both updating the branch simultaneously 😄

**Pull request merged**
