### PR TITLE
fix(BlockMutator): BlockMutator itself adds 'return default' when block returns a value.

### LINKED ISSUE #2283: Block Mutator should report when it returns default value
**Is your feature request related to a problem? Please describe.**
When the BlockMutator removes a block that contains a return statement, it implicitly adds a statement that returns default. However, this is not shown in the output report. The code that is displayed in the report would actually result in a compile error in some cases. 

**Describe the solution you'd like**
I would like the report to explicitly display when a 'return default' is added. 

**Additional context**
This:
CurrentScenario

Should look something like this:
NewScenario

### PR DESCRIPTION
**Pull request by Liam-Rougoor**
Closes #2283.

### CODE REVIEW

**Comment by psfinaki** [comment]
I haven't read the full discussion but looks nice.

One question though - am I right that this doesn't take into consideration the fact that [default literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-71) are relatively new in the C# language? (since 7.1). How hard will it be to implement the older version of this (with explicit type, like `default(T)`).

Also, MSDN says 
> You can use default literal expressions in default value expressions when the target type can be inferred.

I cannot think what are the edge cases when the types actually **cannot** be inferred, but that's probably another argument for using explicit syntax.

**Comment by Liam-Rougoor** [comment]
> One question though - am I right that this doesn't take into consideration the fact that [default literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-71) are relatively new in the C# language? (since 7.1). How hard will it be to implement the older version of this (with explicit type, like `default(T)`).

Good point.

I'm also considering to re-use the `EndingReturnEngine` somehow, which is now responsible for adding the default return under the hood. That one does use the explicit defaults.

**Comment by Liam-Rougoor** [comment]
We are investigating whether this approach is the one we want, or whether we want to fix this issue some other way. Changing the PR to draft.

**Pull request closed without merging**
