### PR TITLE
feat(Mutant coverage): Analyze mutant coverage to improve performance by filtering tests

### PR DESCRIPTION
**Pull request by dupdob**
### this PR is not to be merged for now, it is WIP
Implement mutant coverage, i.e. have the list of tests that goes through each mutant.
see issue #388 for motivation and usage.

Notes:
- control mechanism for mutant control as been revised (method call instead of a property). A method call is imperative to track mutant usage.

### CODE REVIEW

**Comment by dupdob** [comment]
I have issues with one test with namepipe. Works in local, fails on Azure (aren't they the best ones?).
Need to dig into this.

**Comment by dupdob** [comment]
### Current status
Integrated **basic** mutant coverage (i.e. which mutant is actually executed during tests) with VsTest.
Plus, this version skip testing non covered mutants.
Now I will work on detail coverage : which mutants are executed during each test.

Side note: The stability issue with named pipe tests was due to race conditions with the assertion logic. It gave me the idea for a useful helper method.

**Comment by dupdob** [comment]
### Update
- added coverage capture with VsTest. Results are unstable on integration test projects: actual result is 5 mutants are covered by tests (out of 15), but sometimes I get only 3. May be related to a race condition (data is published when the appdomain is tear down).
- tests are now interrupted as soon as a test failure is received (with VsTest), should provide total time reduction by at least 2x up to 20-30x or even more. But no run made against NFluent, waiting for issue #391 to be solved

**Comment by dupdob** [comment]
VsTest now capture and reports covered mutants **per test**!
Performance needs to improve.

**Comment by dupdob** [comment]
Some update on my end: I have been busy fixing an issue on NFluent and preparing a release last week end, but I have been able to implement the optimisation logic: running only the appropriate tests for each mutant. 
On the integration project, it does not bring any visible difference (too small). 
I tried it on NFluent (renamed the assembly to go past issue #391): it seems to be failing at various stage. Performance turns out to be a problem as running each test in isolation is really slow.

Further work needed

**Comment by dupdob** [comment]
I just pushed past days' work. It implements all 4 steps of coverage strategies.
Still issues to be ironed out, and performance kinda sucks, but this is functional.
Optimisation features are now controlled by a flag field in InitialisationProcess

**Comment by dupdob** [comment]
Now I know why the coverage logic fails to send back its results: as explained in this [comment](https://github.com/Microsoft/vstest/issues/1900#issuecomment-458004993No), VsTest kills the testing process if it takes more than 100ms to shut down.

**Comment by Mobrockers** [comment]
Hey @dupdob, how's it going? :) 

Would you mind if we also take a look at this some time?

**Comment by dupdob** [comment]
Of course, I suggest you read my status report and revert to me regarding how to move forward


---
# summary
well, I am still working on NFluent right now and your ping makes me realise that I have been stuck for a while on this PR.
here is my current status:
I am able to reliably identify mutants that are not covered by any test, which allows to skip them during the test phase, saving some time (depending of the test coverage)

I am still unable to RELIABLY identify the mutants covered by each tests.

The main obstacles are:
- reliability issues with (my implementation of) pipes. despite intensive debugging, some lockup still occurs
- asynchronous behaviour in VsTest

## designs
I have went through three design phases/strategy. I'll share them with you:

0. prerequisite: review the active mutant selection component to use a method call (IsActive(int id)) instead of a property. It allows the code to capture which mutants are covered

1. **capture the list of tested mutants**. This is done thanks to (0) and the list of covered mutants are sent back to Stryker using a named pipe. The transmission is triggered by the appdomain shut down event. But there is some stability issue (sometimes result is not transmitted, like 3-5% of the time), probably due to timing issues (appdomain shutdown event processing is limited to two seconds and vstests uses it as well.

2. **capture the list of tested mutants on a per test basis**. I use previous design and runs each test in isolation, which provides me with the list of tested mutants for each tests. I encounter the same stability issue, but I can mitigate it by retrying the run a couple of times. At the end, I get coverage date for 99.8% of the tests (i.e. only 5-8 failures on NFluent test base), **but this approach is almost as slow as the non optimised case**, each test run taking a couple of seconds, it takes roughly 30-40 minutes to get coverage result for NFluent.

3. **capture the list of tested mutants using an inproc data collector**. This time, the tests are run normally, but I use a custom inproc data collector to get coverage date after each test is run. Performance looks very good, but this is very unstable and not usable with NFluent. The first issue was that you need to run tests on a sequential basis (at least for NUnit), otherwise you get asynchronous notification for test runs, meaning coverage data leak across tests. Plus I have severe deadlocks with pipes, I fixed two issues in my code but I am not able to spot any other, I hope the issue lies in my implementation, but there is also a risk the issue my come from async IO being not very friendly with vstest threading model.

After spending two weeks trying to fix my issue, I decided I needed to refresh my mind and work on something simpler

## possible next steps
If you have a different design/strategy in mind, try it, by all means. Otherwise, here is a proposal for you:
1. I can revert my code to design number 2 and push a PR for it. It will allow to release the feature as beta/experimental. Note that those optimisations could be controlled though Stryker options. My code use configuration flags, but those are not exposed as option yet.
1. You can also activate only the basic coverage strategy that should improve performance for many project, plus provide interesting feedback to user (this code is not covered by any test)
1. I can push my latest work is anybody is willing to give a try and find the issue(s) that block me


As usual, I will respond to questions/comments ASAP

keep up the good work

**Comment by Mobrockers** [comment]
@dupdob If you could provide us with the commit id's for each step (1, 2) and push your latest changes, then I'll take a look at it and depending on my experience I'll decide with richard which route we take. Preferably I would continue working on your latest work because that is the route we discussed internally with coworkers as well :) I'll just create new branches from the commits for each step and release based on that. Sound good?

**Comment by dupdob** [comment]
helloI am afraid I can no longer point to the specific commits. 
I restarted effort from scratch along the way.
Plus I fixed bug in the pipe implementations that would have to be back ported.
I am working on a PR that will provide those features. I will push something tomorrow

**Pull request closed without merging**
