### PR TITLE
feat(mutation exclusion): allow property members to be excluded by name

### PR DESCRIPTION
**Pull request by riezebosch**
I've some readonly properties that only provide metadata and would like to ignore:

```
        string IRule.Description => "some description that is pushed to the frontend";
        string IRule.Link => "https://google.com";
```

### CODE REVIEW

**Comment by riezebosch** [comment]
Auto exclude by honoring  the `ExcludeFromCodeCoverage` attribute would even beter fit my purpose: #964 But I guess it still makes sense to expand the filter method to properties.

**Comment by richardwerkman** [comment]
This will cause the `--ignore-methods` option to be quite expanded. Could you please update the documentation? 

Also: this doesn't only target your test cases but all properties. Excluding them seems rigorous as properties are often named the same across a lot of classes. You could add an extra test case for:
`public int Age { get; set; }`

But we can live with this fact so we would like to embrace this feature! But please create an issue first next time so we can discuss a new feature first 🚀

**Comment by riezebosch** [comment]
> This will cause the `--ignore-methods` option to be quite expanded. Could you please update the documentation?
> 
> Also: this doesn't only target your test cases but all properties. Excluding them seems rigorous as properties are often named the same across a lot of classes. You could add an extra test case for:
> `public int Age { get; set; }`
> 
> But we can live with this fact so we would like to embrace this feature! But please create an issue first next time so we can discuss a new feature first 🚀

I'm not sure if I still want this myself since I already dislike the ambiguity of given filter. The use of excluding method-calls seems appropriate since one can't really test the mutations on `ConfigureAwait` for example but excluding method-bodies (like it already does) is a whole different beast.

Since you already accepted my other PR where I can opt-out of testing with the `ExcludeCoverage` attribute you maybe want to restrict this feature even more.

**Pull request closed without merging**
